//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADLauncher.PushSoft {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PushSoft.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetToken", ReplyAction="*")]
        ADLauncher.PushSoft.GetTokenResponse GetToken(ADLauncher.PushSoft.GetTokenRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 token 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPlates", ReplyAction="*")]
        ADLauncher.PushSoft.GetPlatesResponse GetPlates(ADLauncher.PushSoft.GetPlatesRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 token 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHardwares", ReplyAction="*")]
        ADLauncher.PushSoft.GetHardwaresResponse GetHardwares(ADLauncher.PushSoft.GetHardwaresRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 token 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEdges", ReplyAction="*")]
        ADLauncher.PushSoft.GetEdgesResponse GetEdges(ADLauncher.PushSoft.GetEdgesRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 token 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderDesign", ReplyAction="*")]
        ADLauncher.PushSoft.OrderDesignResponse OrderDesign(ADLauncher.PushSoft.OrderDesignRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 token 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderCancelDesign", ReplyAction="*")]
        ADLauncher.PushSoft.OrderCancelDesignResponse OrderCancelDesign(ADLauncher.PushSoft.OrderCancelDesignRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 token 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderCanEdit", ReplyAction="*")]
        ADLauncher.PushSoft.OrderCanEditResponse OrderCanEdit(ADLauncher.PushSoft.OrderCanEditRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 token 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Optimized", ReplyAction="*")]
        ADLauncher.PushSoft.OptimizedResponse Optimized(ADLauncher.PushSoft.OptimizedRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetToken", Namespace="http://tempuri.org/", Order=0)]
        public ADLauncher.PushSoft.GetTokenRequestBody Body;
        
        public GetTokenRequest() {
        }
        
        public GetTokenRequest(ADLauncher.PushSoft.GetTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public GetTokenRequestBody() {
        }
        
        public GetTokenRequestBody(string userId, string password) {
            this.userId = userId;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTokenResponse", Namespace="http://tempuri.org/", Order=0)]
        public ADLauncher.PushSoft.GetTokenResponseBody Body;
        
        public GetTokenResponse() {
        }
        
        public GetTokenResponse(ADLauncher.PushSoft.GetTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTokenResult;
        
        public GetTokenResponseBody() {
        }
        
        public GetTokenResponseBody(string GetTokenResult) {
            this.GetTokenResult = GetTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPlatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPlates", Namespace="http://tempuri.org/", Order=0)]
        public ADLauncher.PushSoft.GetPlatesRequestBody Body;
        
        public GetPlatesRequest() {
        }
        
        public GetPlatesRequest(ADLauncher.PushSoft.GetPlatesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPlatesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        public GetPlatesRequestBody() {
        }
        
        public GetPlatesRequestBody(string token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPlatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPlatesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ADLauncher.PushSoft.GetPlatesResponseBody Body;
        
        public GetPlatesResponse() {
        }
        
        public GetPlatesResponse(ADLauncher.PushSoft.GetPlatesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPlatesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPlatesResult;
        
        public GetPlatesResponseBody() {
        }
        
        public GetPlatesResponseBody(string GetPlatesResult) {
            this.GetPlatesResult = GetPlatesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHardwaresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHardwares", Namespace="http://tempuri.org/", Order=0)]
        public ADLauncher.PushSoft.GetHardwaresRequestBody Body;
        
        public GetHardwaresRequest() {
        }
        
        public GetHardwaresRequest(ADLauncher.PushSoft.GetHardwaresRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHardwaresRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        public GetHardwaresRequestBody() {
        }
        
        public GetHardwaresRequestBody(string token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHardwaresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHardwaresResponse", Namespace="http://tempuri.org/", Order=0)]
        public ADLauncher.PushSoft.GetHardwaresResponseBody Body;
        
        public GetHardwaresResponse() {
        }
        
        public GetHardwaresResponse(ADLauncher.PushSoft.GetHardwaresResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHardwaresResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetHardwaresResult;
        
        public GetHardwaresResponseBody() {
        }
        
        public GetHardwaresResponseBody(string GetHardwaresResult) {
            this.GetHardwaresResult = GetHardwaresResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEdgesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEdges", Namespace="http://tempuri.org/", Order=0)]
        public ADLauncher.PushSoft.GetEdgesRequestBody Body;
        
        public GetEdgesRequest() {
        }
        
        public GetEdgesRequest(ADLauncher.PushSoft.GetEdgesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEdgesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        public GetEdgesRequestBody() {
        }
        
        public GetEdgesRequestBody(string token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEdgesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEdgesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ADLauncher.PushSoft.GetEdgesResponseBody Body;
        
        public GetEdgesResponse() {
        }
        
        public GetEdgesResponse(ADLauncher.PushSoft.GetEdgesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEdgesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetEdgesResult;
        
        public GetEdgesResponseBody() {
        }
        
        public GetEdgesResponseBody(string GetEdgesResult) {
            this.GetEdgesResult = GetEdgesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrderDesignRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OrderDesign", Namespace="http://tempuri.org/", Order=0)]
        public ADLauncher.PushSoft.OrderDesignRequestBody Body;
        
        public OrderDesignRequest() {
        }
        
        public OrderDesignRequest(ADLauncher.PushSoft.OrderDesignRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderDesignRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string orderNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int orderLine;
        
        public OrderDesignRequestBody() {
        }
        
        public OrderDesignRequestBody(string token, string orderNum, int orderLine) {
            this.token = token;
            this.orderNum = orderNum;
            this.orderLine = orderLine;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrderDesignResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OrderDesignResponse", Namespace="http://tempuri.org/", Order=0)]
        public ADLauncher.PushSoft.OrderDesignResponseBody Body;
        
        public OrderDesignResponse() {
        }
        
        public OrderDesignResponse(ADLauncher.PushSoft.OrderDesignResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderDesignResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OrderDesignResult;
        
        public OrderDesignResponseBody() {
        }
        
        public OrderDesignResponseBody(string OrderDesignResult) {
            this.OrderDesignResult = OrderDesignResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrderCancelDesignRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OrderCancelDesign", Namespace="http://tempuri.org/", Order=0)]
        public ADLauncher.PushSoft.OrderCancelDesignRequestBody Body;
        
        public OrderCancelDesignRequest() {
        }
        
        public OrderCancelDesignRequest(ADLauncher.PushSoft.OrderCancelDesignRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderCancelDesignRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string orderNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int orderLine;
        
        public OrderCancelDesignRequestBody() {
        }
        
        public OrderCancelDesignRequestBody(string token, string orderNum, int orderLine) {
            this.token = token;
            this.orderNum = orderNum;
            this.orderLine = orderLine;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrderCancelDesignResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OrderCancelDesignResponse", Namespace="http://tempuri.org/", Order=0)]
        public ADLauncher.PushSoft.OrderCancelDesignResponseBody Body;
        
        public OrderCancelDesignResponse() {
        }
        
        public OrderCancelDesignResponse(ADLauncher.PushSoft.OrderCancelDesignResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderCancelDesignResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OrderCancelDesignResult;
        
        public OrderCancelDesignResponseBody() {
        }
        
        public OrderCancelDesignResponseBody(string OrderCancelDesignResult) {
            this.OrderCancelDesignResult = OrderCancelDesignResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrderCanEditRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OrderCanEdit", Namespace="http://tempuri.org/", Order=0)]
        public ADLauncher.PushSoft.OrderCanEditRequestBody Body;
        
        public OrderCanEditRequest() {
        }
        
        public OrderCanEditRequest(ADLauncher.PushSoft.OrderCanEditRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderCanEditRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string orderNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int orderLine;
        
        public OrderCanEditRequestBody() {
        }
        
        public OrderCanEditRequestBody(string token, string orderNum, int orderLine) {
            this.token = token;
            this.orderNum = orderNum;
            this.orderLine = orderLine;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrderCanEditResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OrderCanEditResponse", Namespace="http://tempuri.org/", Order=0)]
        public ADLauncher.PushSoft.OrderCanEditResponseBody Body;
        
        public OrderCanEditResponse() {
        }
        
        public OrderCanEditResponse(ADLauncher.PushSoft.OrderCanEditResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderCanEditResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OrderCanEditResult;
        
        public OrderCanEditResponseBody() {
        }
        
        public OrderCanEditResponseBody(string OrderCanEditResult) {
            this.OrderCanEditResult = OrderCanEditResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OptimizedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Optimized", Namespace="http://tempuri.org/", Order=0)]
        public ADLauncher.PushSoft.OptimizedRequestBody Body;
        
        public OptimizedRequest() {
        }
        
        public OptimizedRequest(ADLauncher.PushSoft.OptimizedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OptimizedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string numAtCrd;
        
        public OptimizedRequestBody() {
        }
        
        public OptimizedRequestBody(string token, string numAtCrd) {
            this.token = token;
            this.numAtCrd = numAtCrd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OptimizedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OptimizedResponse", Namespace="http://tempuri.org/", Order=0)]
        public ADLauncher.PushSoft.OptimizedResponseBody Body;
        
        public OptimizedResponse() {
        }
        
        public OptimizedResponse(ADLauncher.PushSoft.OptimizedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OptimizedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OptimizedResult;
        
        public OptimizedResponseBody() {
        }
        
        public OptimizedResponseBody(string OptimizedResult) {
            this.OptimizedResult = OptimizedResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : ADLauncher.PushSoft.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<ADLauncher.PushSoft.WebServiceSoap>, ADLauncher.PushSoft.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ADLauncher.PushSoft.GetTokenResponse ADLauncher.PushSoft.WebServiceSoap.GetToken(ADLauncher.PushSoft.GetTokenRequest request) {
            return base.Channel.GetToken(request);
        }
        
        public string GetToken(string userId, string password) {
            ADLauncher.PushSoft.GetTokenRequest inValue = new ADLauncher.PushSoft.GetTokenRequest();
            inValue.Body = new ADLauncher.PushSoft.GetTokenRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            ADLauncher.PushSoft.GetTokenResponse retVal = ((ADLauncher.PushSoft.WebServiceSoap)(this)).GetToken(inValue);
            return retVal.Body.GetTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ADLauncher.PushSoft.GetPlatesResponse ADLauncher.PushSoft.WebServiceSoap.GetPlates(ADLauncher.PushSoft.GetPlatesRequest request) {
            return base.Channel.GetPlates(request);
        }
        
        public string GetPlates(string token) {
            ADLauncher.PushSoft.GetPlatesRequest inValue = new ADLauncher.PushSoft.GetPlatesRequest();
            inValue.Body = new ADLauncher.PushSoft.GetPlatesRequestBody();
            inValue.Body.token = token;
            ADLauncher.PushSoft.GetPlatesResponse retVal = ((ADLauncher.PushSoft.WebServiceSoap)(this)).GetPlates(inValue);
            return retVal.Body.GetPlatesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ADLauncher.PushSoft.GetHardwaresResponse ADLauncher.PushSoft.WebServiceSoap.GetHardwares(ADLauncher.PushSoft.GetHardwaresRequest request) {
            return base.Channel.GetHardwares(request);
        }
        
        public string GetHardwares(string token) {
            ADLauncher.PushSoft.GetHardwaresRequest inValue = new ADLauncher.PushSoft.GetHardwaresRequest();
            inValue.Body = new ADLauncher.PushSoft.GetHardwaresRequestBody();
            inValue.Body.token = token;
            ADLauncher.PushSoft.GetHardwaresResponse retVal = ((ADLauncher.PushSoft.WebServiceSoap)(this)).GetHardwares(inValue);
            return retVal.Body.GetHardwaresResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ADLauncher.PushSoft.GetEdgesResponse ADLauncher.PushSoft.WebServiceSoap.GetEdges(ADLauncher.PushSoft.GetEdgesRequest request) {
            return base.Channel.GetEdges(request);
        }
        
        public string GetEdges(string token) {
            ADLauncher.PushSoft.GetEdgesRequest inValue = new ADLauncher.PushSoft.GetEdgesRequest();
            inValue.Body = new ADLauncher.PushSoft.GetEdgesRequestBody();
            inValue.Body.token = token;
            ADLauncher.PushSoft.GetEdgesResponse retVal = ((ADLauncher.PushSoft.WebServiceSoap)(this)).GetEdges(inValue);
            return retVal.Body.GetEdgesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ADLauncher.PushSoft.OrderDesignResponse ADLauncher.PushSoft.WebServiceSoap.OrderDesign(ADLauncher.PushSoft.OrderDesignRequest request) {
            return base.Channel.OrderDesign(request);
        }
        
        public string OrderDesign(string token, string orderNum, int orderLine) {
            ADLauncher.PushSoft.OrderDesignRequest inValue = new ADLauncher.PushSoft.OrderDesignRequest();
            inValue.Body = new ADLauncher.PushSoft.OrderDesignRequestBody();
            inValue.Body.token = token;
            inValue.Body.orderNum = orderNum;
            inValue.Body.orderLine = orderLine;
            ADLauncher.PushSoft.OrderDesignResponse retVal = ((ADLauncher.PushSoft.WebServiceSoap)(this)).OrderDesign(inValue);
            return retVal.Body.OrderDesignResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ADLauncher.PushSoft.OrderCancelDesignResponse ADLauncher.PushSoft.WebServiceSoap.OrderCancelDesign(ADLauncher.PushSoft.OrderCancelDesignRequest request) {
            return base.Channel.OrderCancelDesign(request);
        }
        
        public string OrderCancelDesign(string token, string orderNum, int orderLine) {
            ADLauncher.PushSoft.OrderCancelDesignRequest inValue = new ADLauncher.PushSoft.OrderCancelDesignRequest();
            inValue.Body = new ADLauncher.PushSoft.OrderCancelDesignRequestBody();
            inValue.Body.token = token;
            inValue.Body.orderNum = orderNum;
            inValue.Body.orderLine = orderLine;
            ADLauncher.PushSoft.OrderCancelDesignResponse retVal = ((ADLauncher.PushSoft.WebServiceSoap)(this)).OrderCancelDesign(inValue);
            return retVal.Body.OrderCancelDesignResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ADLauncher.PushSoft.OrderCanEditResponse ADLauncher.PushSoft.WebServiceSoap.OrderCanEdit(ADLauncher.PushSoft.OrderCanEditRequest request) {
            return base.Channel.OrderCanEdit(request);
        }
        
        public string OrderCanEdit(string token, string orderNum, int orderLine) {
            ADLauncher.PushSoft.OrderCanEditRequest inValue = new ADLauncher.PushSoft.OrderCanEditRequest();
            inValue.Body = new ADLauncher.PushSoft.OrderCanEditRequestBody();
            inValue.Body.token = token;
            inValue.Body.orderNum = orderNum;
            inValue.Body.orderLine = orderLine;
            ADLauncher.PushSoft.OrderCanEditResponse retVal = ((ADLauncher.PushSoft.WebServiceSoap)(this)).OrderCanEdit(inValue);
            return retVal.Body.OrderCanEditResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ADLauncher.PushSoft.OptimizedResponse ADLauncher.PushSoft.WebServiceSoap.Optimized(ADLauncher.PushSoft.OptimizedRequest request) {
            return base.Channel.Optimized(request);
        }
        
        public string Optimized(string token, string numAtCrd) {
            ADLauncher.PushSoft.OptimizedRequest inValue = new ADLauncher.PushSoft.OptimizedRequest();
            inValue.Body = new ADLauncher.PushSoft.OptimizedRequestBody();
            inValue.Body.token = token;
            inValue.Body.numAtCrd = numAtCrd;
            ADLauncher.PushSoft.OptimizedResponse retVal = ((ADLauncher.PushSoft.WebServiceSoap)(this)).Optimized(inValue);
            return retVal.Body.OptimizedResult;
        }
    }
}
