//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteExport.Push {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Push.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetToken", ReplyAction="*")]
        QuoteExport.Push.GetTokenResponse GetToken(QuoteExport.Push.GetTokenRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 token 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPlates", ReplyAction="*")]
        QuoteExport.Push.GetPlatesResponse GetPlates(QuoteExport.Push.GetPlatesRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 token 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHardwares", ReplyAction="*")]
        QuoteExport.Push.GetHardwaresResponse GetHardwares(QuoteExport.Push.GetHardwaresRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 token 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEdges", ReplyAction="*")]
        QuoteExport.Push.GetEdgesResponse GetEdges(QuoteExport.Push.GetEdgesRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 token 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderDesign", ReplyAction="*")]
        QuoteExport.Push.OrderDesignResponse OrderDesign(QuoteExport.Push.OrderDesignRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 token 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderCancelDesign", ReplyAction="*")]
        QuoteExport.Push.OrderCancelDesignResponse OrderCancelDesign(QuoteExport.Push.OrderCancelDesignRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 token 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderCanEdit", ReplyAction="*")]
        QuoteExport.Push.OrderCanEditResponse OrderCanEdit(QuoteExport.Push.OrderCanEditRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 token 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Optimized", ReplyAction="*")]
        QuoteExport.Push.OptimizedResponse Optimized(QuoteExport.Push.OptimizedRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetToken", Namespace="http://tempuri.org/", Order=0)]
        public QuoteExport.Push.GetTokenRequestBody Body;
        
        public GetTokenRequest() {
        }
        
        public GetTokenRequest(QuoteExport.Push.GetTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public GetTokenRequestBody() {
        }
        
        public GetTokenRequestBody(string userId, string password) {
            this.userId = userId;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTokenResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuoteExport.Push.GetTokenResponseBody Body;
        
        public GetTokenResponse() {
        }
        
        public GetTokenResponse(QuoteExport.Push.GetTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTokenResult;
        
        public GetTokenResponseBody() {
        }
        
        public GetTokenResponseBody(string GetTokenResult) {
            this.GetTokenResult = GetTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPlatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPlates", Namespace="http://tempuri.org/", Order=0)]
        public QuoteExport.Push.GetPlatesRequestBody Body;
        
        public GetPlatesRequest() {
        }
        
        public GetPlatesRequest(QuoteExport.Push.GetPlatesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPlatesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        public GetPlatesRequestBody() {
        }
        
        public GetPlatesRequestBody(string token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPlatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPlatesResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuoteExport.Push.GetPlatesResponseBody Body;
        
        public GetPlatesResponse() {
        }
        
        public GetPlatesResponse(QuoteExport.Push.GetPlatesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPlatesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPlatesResult;
        
        public GetPlatesResponseBody() {
        }
        
        public GetPlatesResponseBody(string GetPlatesResult) {
            this.GetPlatesResult = GetPlatesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHardwaresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHardwares", Namespace="http://tempuri.org/", Order=0)]
        public QuoteExport.Push.GetHardwaresRequestBody Body;
        
        public GetHardwaresRequest() {
        }
        
        public GetHardwaresRequest(QuoteExport.Push.GetHardwaresRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHardwaresRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        public GetHardwaresRequestBody() {
        }
        
        public GetHardwaresRequestBody(string token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHardwaresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHardwaresResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuoteExport.Push.GetHardwaresResponseBody Body;
        
        public GetHardwaresResponse() {
        }
        
        public GetHardwaresResponse(QuoteExport.Push.GetHardwaresResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHardwaresResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetHardwaresResult;
        
        public GetHardwaresResponseBody() {
        }
        
        public GetHardwaresResponseBody(string GetHardwaresResult) {
            this.GetHardwaresResult = GetHardwaresResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEdgesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEdges", Namespace="http://tempuri.org/", Order=0)]
        public QuoteExport.Push.GetEdgesRequestBody Body;
        
        public GetEdgesRequest() {
        }
        
        public GetEdgesRequest(QuoteExport.Push.GetEdgesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEdgesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        public GetEdgesRequestBody() {
        }
        
        public GetEdgesRequestBody(string token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEdgesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEdgesResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuoteExport.Push.GetEdgesResponseBody Body;
        
        public GetEdgesResponse() {
        }
        
        public GetEdgesResponse(QuoteExport.Push.GetEdgesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEdgesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetEdgesResult;
        
        public GetEdgesResponseBody() {
        }
        
        public GetEdgesResponseBody(string GetEdgesResult) {
            this.GetEdgesResult = GetEdgesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrderDesignRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OrderDesign", Namespace="http://tempuri.org/", Order=0)]
        public QuoteExport.Push.OrderDesignRequestBody Body;
        
        public OrderDesignRequest() {
        }
        
        public OrderDesignRequest(QuoteExport.Push.OrderDesignRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderDesignRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string orderNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int orderLine;
        
        public OrderDesignRequestBody() {
        }
        
        public OrderDesignRequestBody(string token, string orderNum, int orderLine) {
            this.token = token;
            this.orderNum = orderNum;
            this.orderLine = orderLine;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrderDesignResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OrderDesignResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuoteExport.Push.OrderDesignResponseBody Body;
        
        public OrderDesignResponse() {
        }
        
        public OrderDesignResponse(QuoteExport.Push.OrderDesignResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderDesignResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OrderDesignResult;
        
        public OrderDesignResponseBody() {
        }
        
        public OrderDesignResponseBody(string OrderDesignResult) {
            this.OrderDesignResult = OrderDesignResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrderCancelDesignRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OrderCancelDesign", Namespace="http://tempuri.org/", Order=0)]
        public QuoteExport.Push.OrderCancelDesignRequestBody Body;
        
        public OrderCancelDesignRequest() {
        }
        
        public OrderCancelDesignRequest(QuoteExport.Push.OrderCancelDesignRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderCancelDesignRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string orderNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int orderLine;
        
        public OrderCancelDesignRequestBody() {
        }
        
        public OrderCancelDesignRequestBody(string token, string orderNum, int orderLine) {
            this.token = token;
            this.orderNum = orderNum;
            this.orderLine = orderLine;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrderCancelDesignResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OrderCancelDesignResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuoteExport.Push.OrderCancelDesignResponseBody Body;
        
        public OrderCancelDesignResponse() {
        }
        
        public OrderCancelDesignResponse(QuoteExport.Push.OrderCancelDesignResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderCancelDesignResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OrderCancelDesignResult;
        
        public OrderCancelDesignResponseBody() {
        }
        
        public OrderCancelDesignResponseBody(string OrderCancelDesignResult) {
            this.OrderCancelDesignResult = OrderCancelDesignResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrderCanEditRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OrderCanEdit", Namespace="http://tempuri.org/", Order=0)]
        public QuoteExport.Push.OrderCanEditRequestBody Body;
        
        public OrderCanEditRequest() {
        }
        
        public OrderCanEditRequest(QuoteExport.Push.OrderCanEditRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderCanEditRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string orderNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int orderLine;
        
        public OrderCanEditRequestBody() {
        }
        
        public OrderCanEditRequestBody(string token, string orderNum, int orderLine) {
            this.token = token;
            this.orderNum = orderNum;
            this.orderLine = orderLine;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrderCanEditResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OrderCanEditResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuoteExport.Push.OrderCanEditResponseBody Body;
        
        public OrderCanEditResponse() {
        }
        
        public OrderCanEditResponse(QuoteExport.Push.OrderCanEditResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderCanEditResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OrderCanEditResult;
        
        public OrderCanEditResponseBody() {
        }
        
        public OrderCanEditResponseBody(string OrderCanEditResult) {
            this.OrderCanEditResult = OrderCanEditResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OptimizedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Optimized", Namespace="http://tempuri.org/", Order=0)]
        public QuoteExport.Push.OptimizedRequestBody Body;
        
        public OptimizedRequest() {
        }
        
        public OptimizedRequest(QuoteExport.Push.OptimizedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OptimizedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string numAtCrd;
        
        public OptimizedRequestBody() {
        }
        
        public OptimizedRequestBody(string token, string numAtCrd) {
            this.token = token;
            this.numAtCrd = numAtCrd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OptimizedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OptimizedResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuoteExport.Push.OptimizedResponseBody Body;
        
        public OptimizedResponse() {
        }
        
        public OptimizedResponse(QuoteExport.Push.OptimizedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OptimizedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OptimizedResult;
        
        public OptimizedResponseBody() {
        }
        
        public OptimizedResponseBody(string OptimizedResult) {
            this.OptimizedResult = OptimizedResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : QuoteExport.Push.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<QuoteExport.Push.WebServiceSoap>, QuoteExport.Push.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuoteExport.Push.GetTokenResponse QuoteExport.Push.WebServiceSoap.GetToken(QuoteExport.Push.GetTokenRequest request) {
            return base.Channel.GetToken(request);
        }
        
        public string GetToken(string userId, string password) {
            QuoteExport.Push.GetTokenRequest inValue = new QuoteExport.Push.GetTokenRequest();
            inValue.Body = new QuoteExport.Push.GetTokenRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            QuoteExport.Push.GetTokenResponse retVal = ((QuoteExport.Push.WebServiceSoap)(this)).GetToken(inValue);
            return retVal.Body.GetTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuoteExport.Push.GetPlatesResponse QuoteExport.Push.WebServiceSoap.GetPlates(QuoteExport.Push.GetPlatesRequest request) {
            return base.Channel.GetPlates(request);
        }
        
        public string GetPlates(string token) {
            QuoteExport.Push.GetPlatesRequest inValue = new QuoteExport.Push.GetPlatesRequest();
            inValue.Body = new QuoteExport.Push.GetPlatesRequestBody();
            inValue.Body.token = token;
            QuoteExport.Push.GetPlatesResponse retVal = ((QuoteExport.Push.WebServiceSoap)(this)).GetPlates(inValue);
            return retVal.Body.GetPlatesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuoteExport.Push.GetHardwaresResponse QuoteExport.Push.WebServiceSoap.GetHardwares(QuoteExport.Push.GetHardwaresRequest request) {
            return base.Channel.GetHardwares(request);
        }
        
        public string GetHardwares(string token) {
            QuoteExport.Push.GetHardwaresRequest inValue = new QuoteExport.Push.GetHardwaresRequest();
            inValue.Body = new QuoteExport.Push.GetHardwaresRequestBody();
            inValue.Body.token = token;
            QuoteExport.Push.GetHardwaresResponse retVal = ((QuoteExport.Push.WebServiceSoap)(this)).GetHardwares(inValue);
            return retVal.Body.GetHardwaresResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuoteExport.Push.GetEdgesResponse QuoteExport.Push.WebServiceSoap.GetEdges(QuoteExport.Push.GetEdgesRequest request) {
            return base.Channel.GetEdges(request);
        }
        
        public string GetEdges(string token) {
            QuoteExport.Push.GetEdgesRequest inValue = new QuoteExport.Push.GetEdgesRequest();
            inValue.Body = new QuoteExport.Push.GetEdgesRequestBody();
            inValue.Body.token = token;
            QuoteExport.Push.GetEdgesResponse retVal = ((QuoteExport.Push.WebServiceSoap)(this)).GetEdges(inValue);
            return retVal.Body.GetEdgesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuoteExport.Push.OrderDesignResponse QuoteExport.Push.WebServiceSoap.OrderDesign(QuoteExport.Push.OrderDesignRequest request) {
            return base.Channel.OrderDesign(request);
        }
        
        public string OrderDesign(string token, string orderNum, int orderLine) {
            QuoteExport.Push.OrderDesignRequest inValue = new QuoteExport.Push.OrderDesignRequest();
            inValue.Body = new QuoteExport.Push.OrderDesignRequestBody();
            inValue.Body.token = token;
            inValue.Body.orderNum = orderNum;
            inValue.Body.orderLine = orderLine;
            QuoteExport.Push.OrderDesignResponse retVal = ((QuoteExport.Push.WebServiceSoap)(this)).OrderDesign(inValue);
            return retVal.Body.OrderDesignResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuoteExport.Push.OrderCancelDesignResponse QuoteExport.Push.WebServiceSoap.OrderCancelDesign(QuoteExport.Push.OrderCancelDesignRequest request) {
            return base.Channel.OrderCancelDesign(request);
        }
        
        public string OrderCancelDesign(string token, string orderNum, int orderLine) {
            QuoteExport.Push.OrderCancelDesignRequest inValue = new QuoteExport.Push.OrderCancelDesignRequest();
            inValue.Body = new QuoteExport.Push.OrderCancelDesignRequestBody();
            inValue.Body.token = token;
            inValue.Body.orderNum = orderNum;
            inValue.Body.orderLine = orderLine;
            QuoteExport.Push.OrderCancelDesignResponse retVal = ((QuoteExport.Push.WebServiceSoap)(this)).OrderCancelDesign(inValue);
            return retVal.Body.OrderCancelDesignResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuoteExport.Push.OrderCanEditResponse QuoteExport.Push.WebServiceSoap.OrderCanEdit(QuoteExport.Push.OrderCanEditRequest request) {
            return base.Channel.OrderCanEdit(request);
        }
        
        public string OrderCanEdit(string token, string orderNum, int orderLine) {
            QuoteExport.Push.OrderCanEditRequest inValue = new QuoteExport.Push.OrderCanEditRequest();
            inValue.Body = new QuoteExport.Push.OrderCanEditRequestBody();
            inValue.Body.token = token;
            inValue.Body.orderNum = orderNum;
            inValue.Body.orderLine = orderLine;
            QuoteExport.Push.OrderCanEditResponse retVal = ((QuoteExport.Push.WebServiceSoap)(this)).OrderCanEdit(inValue);
            return retVal.Body.OrderCanEditResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuoteExport.Push.OptimizedResponse QuoteExport.Push.WebServiceSoap.Optimized(QuoteExport.Push.OptimizedRequest request) {
            return base.Channel.Optimized(request);
        }
        
        public string Optimized(string token, string numAtCrd) {
            QuoteExport.Push.OptimizedRequest inValue = new QuoteExport.Push.OptimizedRequest();
            inValue.Body = new QuoteExport.Push.OptimizedRequestBody();
            inValue.Body.token = token;
            inValue.Body.numAtCrd = numAtCrd;
            QuoteExport.Push.OptimizedResponse retVal = ((QuoteExport.Push.WebServiceSoap)(this)).Optimized(inValue);
            return retVal.Body.OptimizedResult;
        }
    }
}
